<?php
$seo["social"]="";
$seo["chat"]="";
$seo["quote"]="";
$seo["call"]="";
$seo["logo"]="";
$seo["logo1"]="";
$seo["home"]="";
$seo["products"]="";
$seo["services"]="";
$seo["support"]="";
$seo["telecom"]="";
$seo["freesolution"]="";
$seo["readmore"]="";
$seo["online_marketing"]="";
$seo["designing"]="";
$seo["mobile_application"]="";
$seo["network"]="";
$seo["php"]="";
$seo["web_development"]="";
$seo["download_link"]="";
$seo["client"]="";
$seo["website"]="";
$seo["callcenter"]="";
$seo["networks"]="";
$seo["consult_business"]="";
?>